### PR TITLE
Sharness tests

### PR DESCRIPTION
**Pull request by chriscool**
Add Sharness tests to test migrations.
These tests use docker so that migrations can be tested without polluting the test host.
These tests also use ipfs-update to install different versions of ipfs.

### CODE REVIEW

**Comment by chriscool** [comment]
Could someone with access rights add Travis-CI builds to this repo?

**Comment by chriscool** [comment]
cc @whyrusleeping @jbenet @lgierth @RichardLitt

**Comment by whyrusleeping** [comment]
sure thing

**Comment by whyrusleeping** [comment]
enabled

**Comment by chriscool** [comment]
Thanks! I will push something to have the test run...

**Comment by chriscool** [comment]
It looks like I did something wrong when trying to manually vendor ipfs-update in `sharness/dependencies`.

If someone could have a look, or suggest a good way to do it that would be really nice!

**Comment by chriscool** [comment]
The Travis log is:

```
Setting environment variables from .travis.yml

$ export TEST_VERBOSE=1

2.72s$ eval "$(gimme 1.5.2)"

go version go1.5.2 linux/amd64

$ export GOPATH=$HOME/gopath

$ export PATH=$HOME/gopath/bin:$PATH

$ mkdir -p $HOME/gopath/src/github.com/ipfs/fs-repo-migrations

$ rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/ipfs/fs-repo-migrations/

$ export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/ipfs/fs-repo-migrations

$ cd $HOME/gopath/src/github.com/ipfs/fs-repo-migrations

$ gimme version

v0.2.3

$ go version

go version go1.5.2 linux/amd64
go.env

$ go env

GOARCH="amd64"

GOBIN=""

GOEXE=""

GOHOSTARCH="amd64"

GOHOSTOS="linux"

GOOS="linux"

GOPATH="/home/travis/gopath"

GORACE=""

GOROOT="/home/travis/.gimme/versions/go1.5.2.linux.amd64"

GOTOOLDIR="/home/travis/.gimme/versions/go1.5.2.linux.amd64/pkg/tool/linux_amd64"

GO15VENDOREXPERIMENT=""

CC="gcc"

GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"

CXX="g++"

CGO_ENABLED="1"

37.77s$ go get -t -v ./...

Fetching https://golang.org/x/net/context?go-get=1

Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)

get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1

get "golang.org/x/net/context": verifying non-authoritative meta tag

Fetching https://golang.org/x/net?go-get=1

Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)

golang.org/x/net (download)

Fetching https://gopkg.in/check.v1?go-get=1

Parsing meta tags from https://gopkg.in/check.v1?go-get=1 (status code 200)

get "gopkg.in/check.v1": found meta tag main.metaImport{Prefix:"gopkg.in/check.v1", VCS:"git", RepoRoot:"https://gopkg.in/check.v1"} at https://gopkg.in/check.v1?go-get=1

gopkg.in/check.v1 (download)

Fetching https://launchpad.net/gocheck?go-get=1

Parsing meta tags from https://launchpad.net/gocheck?go-get=1 (status code 200)

get "launchpad.net/gocheck": found meta tag main.metaImport{Prefix:"launchpad.net/gocheck", VCS:"bzr", RepoRoot:"https://launchpad.net/~niemeyer/gocheck/trunk"} at https://launchpad.net/gocheck?go-get=1

launchpad.net/gocheck (download)

github.com/ipfs/fs-repo (download)

# cd .; git clone https://github.com/ipfs/fs-repo /home/travis/gopath/src/github.com/ipfs/fs-repo

Cloning into '/home/travis/gopath/src/github.com/ipfs/fs-repo'...

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/ipfs/fs-repo/'

package github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore: exit status 128

package github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query: cannot find package "github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query (from $GOPATH)

github.com/ipfs/fs-repo-migrations (download)

# cd /home/travis/gopath/src/github.com/ipfs/fs-repo-migrations; git symbolic-ref HEAD

fatal: ref HEAD is not a symbolic ref

/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations on detached head; repairing

package github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil: cannot find package "github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil (from $GOPATH)

github.com/onsi/ginkgo (download)

github.com/onsi/gomega (download)

github.com/jbenet/goprocess (download)

github.com/jbenet/go-cienv (download)

package github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update: cannot find package "github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update (from $GOPATH)

package github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/test-dist: cannot find package "github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/test-dist" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/test-dist (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/test-dist (from $GOPATH)

package github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/util: cannot find package "github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/util" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/util (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations/sharness/dependencies/ipfs-update/util (from $GOPATH)

The command "eval go get -t -v ./..." failed. Retrying, 2 of 3.

github.com/ipfs/fs-repo (download)

# cd .; git clone https://github.com/ipfs/fs-repo /home/travis/gopath/src/github.com/ipfs/fs-repo

Cloning into '/home/travis/gopath/src/github.com/ipfs/fs-repo'...

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/ipfs/fs-repo/'

package github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore: exit status 128

package github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query: cannot find package "github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore/query (from $GOPATH)

github.com/ipfs/fs-repo-migrations (download)

package github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil: cannot find package "github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/fs-repo-migrations/ipfs-1-to-2/goleveldb/leveldb/testutil (from $GOPATH)

The command "eval go get -t -v ./..." failed. Retrying, 3 of 3.
```

and there are some strange things in it like:

```
# cd .; git clone https://github.com/ipfs/fs-repo /home/travis/gopath/src/github.com/ipfs/fs-repo

Cloning into '/home/travis/gopath/src/github.com/ipfs/fs-repo'...

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/ipfs/fs-repo/'

package github.com/ipfs/fs-repo/migrations/ipfs-1-to-2/go-datastore: exit status 128
```

**Comment by chriscool** [comment]
Extract from IRC discussion about this:

```
(12:04:26) whyrusleeping: chriscool: i cant tell why it does a 'go get -t -v ./...'
(12:04:29) whyrusleeping: thats weird to me
(12:06:07) chriscool: whyrusleeping: ok thanks anyway
(12:06:22) whyrusleeping: chriscool: try adding a Makefile to the root of the fs-repo-migrations repo
(12:06:31) whyrusleeping: and maybe give it a rule for 'install' that does 'go install'
(12:07:00) chriscool: whyrusleeping: ok I will take a look at that
```

**Comment by chriscool** [comment]
Following discussion on IRC:

```
(12:21:57) chriscool: whyrusleeping: if you look at https://travis-ci.org/ipfs/ipfs-update/builds/95658134 it does go get -t -v ./... and it works well
(12:22:35) chriscool: also the .travis.yml are the same for ipfs-update and fs-repo-migrations
(12:22:40) whyrusleeping: chriscool: yeah, but i'm thinking that something weird might be going on in the fs-repo-migrations repo that we don't want
(12:22:51) whyrusleeping: like, some code in a vendor dir somewhere that breaks on go get

(12:48:22) chriscool: whyrusleeping: I manually vendor ipfs-update into "fs-repo-migrations/sharness/dependencies" in this commit: https://github.com/chriscool/fs-repo-migrations/commit/0bda7b873a2c787f2174831a934a20667ed45db8
(12:48:43) chriscool: do you think the Travis problem comes from this?
(12:53:23) whyrusleeping: chriscool: i don't think so... we do that in go-ipfs
(12:53:29) whyrusleeping: did the Makefile thing work?
(12:53:46) whyrusleeping: we don't need the go get to run in any case because we vendor our dependencies
```

**Comment by chriscool** [comment]
With the 'install' target in the Makefile, there is now:

```
*** installing bin/fs-repo-migrations ***

go build  -o bin/fs-repo-migrations ../

*** installing bin/ipfs-update ***

go build  -o bin/ipfs-update ./dependencies/ipfs-update

dependencies/ipfs-update/main.go:10:2: cannot find package "github.com/codegangsta/cli" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/codegangsta/cli (from $GOROOT)

	/home/travis/gopath/src/github.com/codegangsta/cli (from $GOPATH)

dependencies/ipfs-update/versions.go:9:2: cannot find package "github.com/ipfs/go-ipfs-api" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/go-ipfs-api (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/go-ipfs-api (from $GOPATH)

dependencies/ipfs-update/install.go:14:2: cannot find package "github.com/ipfs/ipfs-update/test-dist" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/ipfs-update/test-dist (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/ipfs-update/test-dist (from $GOPATH)

dependencies/ipfs-update/install.go:15:2: cannot find package "github.com/ipfs/ipfs-update/util" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/ipfs/ipfs-update/util (from $GOROOT)

	/home/travis/gopath/src/github.com/ipfs/ipfs-update/util (from $GOPATH)

dependencies/ipfs-update/install.go:16:2: cannot find package "github.com/whyrusleeping/stump" in any of:

	/home/travis/.gimme/versions/go1.5.2.linux.amd64/src/github.com/whyrusleeping/stump (from $GOROOT)

	/home/travis/gopath/src/github.com/whyrusleeping/stump (from $GOPATH)

make: *** [bin/ipfs-update] Error 1

The command "make" exited with 2.

Done. Your build exited with 1.
```

So yeah the problem is that it needs ipfs-update dependencies too.

**Comment by jbenet** [comment]
at a cursory look this LGTM, but @whyrusleeping's review will be best here.

**Comment by whyrusleeping** [comment]
This LGTM as well. Lets merge it so we can get even more awesomer tests in!

**Pull request merged**
