### PR TITLE
sharness: add pin migration test

### PR DESCRIPTION
**Pull request by chriscool**
Pins should continue to be there after a migration or a revert.

### CODE REVIEW

**Comment by chriscool** [comment]
Unfortunately it looks like indirect pined are removed when reverting a 2 to 3 migration.
I get the following error:

```
expecting success: 

> diff -u all_actual1_sorted all_actual3_sorted
--- all_actual1_sorted  2016-01-22 15:42:26.998833283 +0000
+++ all_actual3_sorted  2016-01-22 15:42:26.998833283 +0000
@@ -1,18 +1,9 @@
 QmNyZVFbgvmzguS2jVMRb8PQMNcCMJrn9E3doDhBbcPNTY recursive
 QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB recursive
-QmRsBC3Y2G6VRPYGAVpZczx1W7Xw54MtM1NcLKTkn6rx3U indirect
-QmRsCaNBMkweZ9vHT5PJRd2TT9rtNKEKyuognCEVxZxF1H indirect
-QmSkjTornLY72QhmK9NvAz26815pTaoAL42rF8Qi3w2WBP indirect
-QmTUTQAgeVfughDSFukMZLbfGvetDJY7Ef5cDXkKK4abKC indirect
 QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ recursive
 QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn recursive
-QmV1aiVgpDknKQugrK59uBUbMrPnsQM1F9FXbFcfgEvUvH indirect
-QmW98gV71Ns4bX7QbgWAqLiGF3SDC1JpveZSgBh4ExaSAd indirect
 QmXarR6rgkQ2fDSHjSY5nM2kuCXKYGViky5nohtwgF65Ec recursive
 QmXifYTiYxz8Nxt3LmjaxtQNLYkjdh324L4r81nZSadoST recursive
 QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7 recursive
 QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y recursive
 QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V recursive
-QmZrr4Pzqp3NnMzMfbMhNe7LghfoUFHVx7c9Po9GZrhKZ7 indirect
-QmaN3PtyP8DcVGHi3Q2Fcp7CfAFVcVXKddWbHoNvaA41zf indirect
-QmbgX4aXhSSY88GHmPQ4roizD8wFwPX8jzTLjc8VAp89x4 indirect

not ok 28 - list of pinned object hasn't changed
```

**Comment by chriscool** [comment]
@whyrusleeping do you have an idea why the indirect pins are lost when reverting the migration?

**Comment by chriscool** [comment]
Thanks @whyrusleeping for the patch that fixes the problem!

**Comment by whyrusleeping** [comment]
woooo! this LGTM!

**Pull request merged**
