### PR TITLE
sharness: remove duplicated sharness dependency

### PR DESCRIPTION
**Pull request by chriscool**
As ipfs-update has been vendored in https://github.com/ipfs/fs-repo-migrations/tree/master/Godeps/_workspace/src/github.com/ipfs/ipfs-update it is not needed anymore in https://github.com/ipfs/fs-repo-migrations/tree/master/sharness/dependencies/ipfs-update so let's remove it.

### CODE REVIEW

**Comment by jbenet** [comment]
Can we use gx to vendor these?

**Comment by chriscool** [comment]
I recently asked @whyrusleeping and he told me it was not possible yet.

**Comment by chriscool** [comment]
So I have to change the Makefile to make the build use ipfs-update from Godeps, but unfortunately it fails with:

```
*** installing bin/ipfs-update ***
go build  -o bin/ipfs-update ../Godeps/_workspace/src/github.com/ipfs/ipfs-update
can't load package: package github.com/ipfs/fs-repo-migrations/Godeps/_workspace/src/github.com/ipfs/ipfs-update: no buildable Go source files in /home/utilisateur/gocode/src/github.com/ipfs/fs-repo-migrations/Godeps/_workspace/src/github.com/ipfs/ipfs-update
make: *** [bin/ipfs-update] Erreur 1
```

So I wonder if it has been properly vendored in Godeps.

**Comment by chriscool** [comment]
@whyrusleeping could you take a look?

**Comment by whyrusleeping** [comment]
Looked to me like Godeps didnt grab all the source it needed. Pushed a fix

**Comment by chriscool** [comment]
Yeah your fix works on my machine! Thanks!

**Pull request merged**
