### PR TITLE
Check objects and add gc

### PR DESCRIPTION
**Pull request by chriscool**
This should take care of the 2 main points in issue #21 (make the 2-3-pins test check if objects are there too).

### CODE REVIEW

**Comment by chriscool** [comment]
There is the following error when calling `ipfs repo gc` after the migration:

```
expecting success: 
	exec_docker "$DOCID" "ipfs repo gc"

Error: merkledag: not found

not ok 23 - 'ipfs repo gc' succeeds
```

@whyrusleeping could you take a look?

**Comment by chriscool** [comment]
It looks like the "Error: merkledag: not found" comes from: https://github.com/ipfs/go-ipfs/blob/master/merkledag/merkledag.go#L102

**Comment by whyrusleeping** [comment]
@chriscool rebase on latest master and give it another try, I also fixed an issue reverting from 3 to 2 here: https://github.com/ipfs/fs-repo-migrations/pull/23

**Comment by chriscool** [comment]
@whyrusleeping  rebase done. Yeah, at least the tests pass on my machine. Thanks!

**Comment by chriscool** [comment]
Travis is happy too :-)

**Comment by whyrusleeping** [comment]
@chriscool awesome, thanks!

**Pull request merged**
