### PR TITLE
Test repo version

### PR DESCRIPTION
**Pull request by chriscool**
Test many migrations and test that the repo version is right after each migration.

### CODE REVIEW

**Comment by chriscool** [comment]
On my machine I get the following error:

```
expecting success: 
		exec_docker "$DOCID" "$GUEST_IPFS_UPDATE --verbose install $VERSION" >actual 2>&1 ||
		test_fsh cat actual

> cat actual
daemon check failed: open /root/.ipfs/api: no such file or directory
fetching ipfs version v0.4.0-dev
  - using GOOS=linux and GOARCH=amd64
  - fetching "/ipns/dist.ipfs.io/go-ipfs/v0.4.0-dev/go-ipfs_v0.4.0-dev_linux-amd64.tar.gz"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.0-dev/go-ipfs_v0.4.0-dev_linux-amd64.tar.gz
  - writing to /tmp/ipfs-update093944932/go-ipfs_v0.4.0-dev_linux-amd64.tar.gz
  - extracting binary to tempdir:  /tmp/ipfs-update998223577/ipfs-new
binary downloaded, verifying...
  - running init in '/root/.ipfs/update-staging/test906562675' with new binary
  - checking new binary outputs correct version
  - tweaking test config to avoid external interference
  - starting up daemon
  - waiting on daemon to come online
  - found api file
  - checking that we can add and cat a file
  - checking that file shows up in ipfs refs local
  - killing test daemon
success!
stashing old binary
  - moving /usr/local/bin/ipfs to /root/.ipfs/old-bin/ipfs-v0.3.10
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  - old repo version is 2
ERROR: Migration Failed:  failed to find migrations binary
  - repo version of new binary is  3
  - Migration required
  - checking for migrations binary...
  - migrations not found on system, attempting to install
could not find or install fs-repo-migrations, please manually install it
before running ipfs-update again.
install failed, reverting changes...
ERROR: failed to find migrations binary 

not ok 14 - 'ipfs-update install' works for v0.4.0-dev

```

**Comment by chriscool** [comment]
Same error on Travis.
It looks like fs-repo-migrations is not found.

**Comment by chriscool** [comment]
I think we have to change the PATH so that fs-repo-migrations can be found.
I will send something.

**Comment by chriscool** [comment]
I added a commit to change the PATH when running ipfs-update and it works.

The tests still don't fully pass because the repository version is not downgraded when updating from 0.4.0-dev to 0.3.8. I am not sure if this is a bug or not.

**Comment by whyrusleeping** [comment]
Yeah, when downgrading we have to run it manually. I havent taught ipfs-update how to do that

**Comment by chriscool** [comment]
Ok, I will not check the repo version then after downgrading.

**Comment by jbenet** [comment]
No, this should be fixed in the appropriate fs-repo-migration.

Please do not change tests to suit incomplete implementations. Worst case
make it a known breakage, but let's actually fix those!

**Comment by whyrusleeping** [comment]
No. The issue is that when using ipfs update to install a lower version of ipfs, ipfs-update will not run the fs-repo-migrations in reverse (by design). All we need to do is manually run the ipfs-2-to-3 with `-revert`

**Comment by chriscool** [comment]
Ok, the last patch runs  the ipfs-2-to-3 with `-revert`.

**Comment by chriscool** [comment]
There is this interesting crash in one of the Travis tests:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x5b559e]
goroutine 1 [running]:
github.com/ipfs/go-ipfs/repo/fsrepo.(*FSRepo).GetStorageUsage.func1(0xc8201efee0, 0x20, 0x0, 0x0, 0x7f3dc3baa518, 0xc8201f1b90, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:565 +0x3e
path/filepath.walk(0xc8201efd40, 0x15, 0x7f3dc3baa030, 0xc82020aaa0, 0xc8200fb7c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc820272a40, 0xb, 0x7f3dc3baa030, 0xc8201e54a0, 0xc8200fb7c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc820272a40, 0xb, 0xc8200fb7c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/path/filepath/path.go:396 +0xe1
github.com/ipfs/go-ipfs/repo/fsrepo.(*FSRepo).GetStorageUsage(0xc82019aa00, 0x2, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:567 +0xa7
github.com/ipfs/go-ipfs/repo.(*ref).GetStorageUsage(0xc8201700c0, 0x411348, 0x0, 0x0)
	<autogenerated>:22 +0x5c
github.com/ipfs/go-ipfs/core/corerepo.(*GC).maybeGC(0xc8201ec940, 0x7f3dc3baaaf0, 0xc82019a9c0, 0xc, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/corerepo/gc.go:162 +0x65
github.com/ipfs/go-ipfs/core/corerepo.ConditionalGC(0x7f3dc3baaaf0, 0xc82019a9c0, 0xc82006c580, 0xc, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/corerepo/gc.go:158 +0x86
github.com/ipfs/go-ipfs/core/commands.glob.func18(0x7f3dc3baa9c8, 0xc8200fc540, 0x7f3dc3baab80, 0xc820198e00)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/cat.go:48 +0x2a8
github.com/ipfs/go-ipfs/commands.(*Command).Call(0x1429660, 0x7f3dc3baa9c8, 0xc8200fc540, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/command.go:110 +0x471
main.callCommand(0x7f3dc3baaaf0, 0xc82019a940, 0x7f3dc3baa9c8, 0xc8200fc540, 0x1429660, 0x14186a0, 0x0, 0x0, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:343 +0xa44
main.(*cmdInvocation).Run(0xc82019a8c0, 0x7f3dc3baaaf0, 0xc82019a940, 0x0, 0x0, 0x0, 0x0)
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:186 +0x1e5
main.main()
	/Users/dignifiedquire/opensource/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:151 +0x65b
```

**Comment by whyrusleeping** [comment]
@chriscool that failure was on 0.3.11 right? Its been fixed (i'm fairly certain) in 0.4.0

**Comment by chriscool** [comment]
@whyrusleeping it looks like it is an error with 0.4.0-dev. Before the failure we install 0.4.0-dev:

```
expecting success: 

		DOCPWD=$(exec_docker "$DOCID" "pwd") &&
		DOCPATH=$(exec_docker "$DOCID" "echo \$PATH") &&
		NEWPATH="$DOCPWD/sharness/bin:$DOCPATH" &&
		exec_docker "$DOCID" "export PATH=\"$NEWPATH\" && $GUEST_IPFS_UPDATE --verbose install $VERSION" >actual 2>&1 ||
		test_fsh cat actual

ok 15 - 'ipfs-update install' works for v0.4.0-dev

expecting success: 

		grep "fetching ipfs version $VERSION" actual &&
		grep "installation complete." actual ||
		test_fsh cat actual

fetching ipfs version v0.4.0-dev
installation complete.

ok 16 - 'ipfs-update install' output looks good

expecting success: 

		exec_docker "$DOCID" "$GUEST_IPFS_UPDATE version" >actual

ok 17 - 'ipfs-update version' works for v0.4.0-dev

expecting success: 

		echo "$VERSION" >expected &&
		test_cmp expected actual

ok 18 - 'ipfs-update version' output looks good

expecting success: 

	exec_docker "$DOCID" "ipfs pin ls --type=recursive" > recurse_actual2 &&
	grep "$HASH_DIR1" recurse_actual2 ||
	test_fsh cat recurse_actual2
QmNyZVFbgvmzguS2jVMRb8PQMNcCMJrn9E3doDhBbcPNTY recursive

ok 19 - added dir is still pinned recursively

expecting success: 

	exec_docker "$DOCID" "ipfs pin ls --type=all" > all_actual2 &&
	test_sort_cmp all_actual1 all_actual2

ok 20 - list of pinned object hasn't changed

expecting success: 

	exec_docker "$DOCID" "ipfs cat $HASH_FILE6" >FILE6_b &&
	exec_docker "$DOCID" "ipfs cat $HASH_FILE5" >FILE5_b &&
	exec_docker "$DOCID" "ipfs cat $HASH_FILE4" >FILE4_b &&
	exec_docker "$DOCID" "ipfs cat $HASH_FILE3" >FILE3_b &&
	exec_docker "$DOCID" "ipfs cat $HASH_FILE2" >FILE2_b &&
	exec_docker "$DOCID" "ipfs cat $HASH_FILE1" >FILE1_b &&
	exec_docker "$DOCID" "ipfs ls $HASH_DIR3"   >DIR3_b &&
	exec_docker "$DOCID" "ipfs ls $HASH_DIR4"   >DIR4_b &&
	exec_docker "$DOCID" "ipfs ls $HASH_DIR2"   >DIR2_b &&
	exec_docker "$DOCID" "ipfs ls $HASH_DIR1"   >DIR1_b
```

**Comment by whyrusleeping** [comment]
@chriscool what is the issue here? the test failures disappeared

**Comment by chriscool** [comment]
There was a crash in a previous test. Anyway the crash was not related so you can merge this.

**Comment by whyrusleeping** [comment]
@chriscool you're gonna have to rebase this

**Comment by whyrusleeping** [comment]
LGTM!

**Pull request merged**
